apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
    - name: api
      port: {{ .Values.broker.service.ports.api.port }}
      targetPort: {{ .Values.broker.service.ports.api.targetPort }}
      protocol: {{ .Values.broker.service.ports.api.protocol }}
      {{- if and (or (eq .Values.broker.service.type "NodePort") (eq .Values.broker.service.type "LoadBalancer")) (not (empty .Values.broker.service.ports.api.nodePort)) }}
      nodePort: {{ .Values.broker.service.ports.api.nodePort }}
      {{- end }}
  selector:
    {{- include "broker.selectorLabels" . | nindent 4 }}
