apiVersion: v1
kind: Service
metadata:
  name: {{ include "mintaka.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mintaka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mintaka.service.type }}
  ports:
    - name: api
      port: {{ .Values.mintaka.service.ports.api.port }}
      targetPort: {{ .Values.mintaka.service.ports.api.targetPort }}
      protocol: {{ .Values.mintaka.service.ports.api.protocol }}
      {{- if and (or (eq .Values.mintaka.service.type "NodePort") (eq .Values.mintaka.service.type "LoadBalancer")) (not (empty .Values.mintaka.service.ports.api.nodePort)) }}
      nodePort: {{ .Values.mintaka.service.ports.api.nodePort }}
      {{- end }}
  selector:
    {{- include "mintaka.selectorLabels" . | nindent 4 }}
