apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescaledb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.timescaledb.service.type }}
  ports:
    - name: db
      port: {{ .Values.timescaledb.service.ports.db.port }}
      targetPort: {{ .Values.timescaledb.service.ports.db.targetPort }}
      protocol: {{ .Values.timescaledb.service.ports.db.protocol }}
      {{- if and (or (eq .Values.timescaledb.service.type "NodePort") (eq .Values.timescaledb.service.type "LoadBalancer")) (not (empty .Values.timescaledb.service.ports.db.nodePort)) }}
      nodePort: {{ .Values.timescaledb.service.ports.db.nodePort }}
      {{- end }}
  selector:
    {{- include "timescaledb.selectorLabels" . | nindent 4 }}
