# Default values for the application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# String to partially override application.fullname template (will maintain the release name).
nameOverride: ""
# String to fully override application.fullname template.
fullnameOverride: ""
# Deploy all the components in specific K8s node(s).
chartNodeSelector: {}

# Component mintaka values.
mintaka:
  tier: external
  replicaCount: 1

  # Configuration of the container image.
  imagePullSecrets: []
  image:
    repository: fiware/mintaka
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.7.0"
    pullPolicy: IfNotPresent
  # Configuration of the service: type and ports.
  service:
    type: NodePort
    ports:
      api:
        port: 8080
        targetPort: 8080
        containerPort: 8080
        nodePort: ""
        protocol: TCP

  resources: {}
  autoscaling:
    enabled: false
  podSecurityContext: {}
  securityContext: {}
    
  envVars:
    database: orion

  # Configure this parameters to deploy the component in specific K8s node(s).
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Component timescaledb values.
timescaledb:
  tier: internal
  replicaCount: 1

  # Configuration of the container image.
  imagePullSecrets: []
  image:
    repository: timescale/timescaledb-postgis
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest-pg12"
    pullPolicy: IfNotPresent
  # Configuration of the service: type and ports.
  service:
    type: ClusterIP
    ports:
      db:
        port: 5432
        targetPort: 5432
        containerPort: 5432
        nodePort: ""
        protocol: TCP

  resources: {}
  autoscaling:
    enabled: false
  podSecurityContext: {}
  securityContext:
    allowPrivilegeEscalation: false
    
  envVars:
    user: orion
    password: 0r10n
    hostAuthMethod: trust

  # Component data persistence
  persistence:
    enabled: true
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 500Mi

  # Configure this parameters to deploy the component in specific K8s node(s).
  nodeSelector: {}
  tolerations: []
  affinity: {}
